### ISSUE TITLE
ListItems has copy-wasted handlers

### ISSUE THREAD

**Issue by dagwud** [EvanKnowles/SecretFightClub#16]
ListItems incorrectly defines getHandlers() to return the handlers from new item, so it passes you into the new item process and you end up creating dodgy items.

**Comment by EvanKnowles** [comment]
Yeah, some guy went and copy pasted and did that a lot.

**Comment by dagwud** [comment]
Obviously he didn’t know what he was doing. He probably should’ve spent more time figuring out the codebase before hacking away ;)
