### ISSUE TITLE
Add ability to remove items from DB

### ISSUE THREAD

**Issue by dagwud** [EvanKnowles/SecretFightClub#17]
Started doing it in ListItemsHandler but it’s not working

Supposed to be triggered via /listitems rm id1,id2,id3...

**Comment by EvanKnowles** [comment]
`/listitems` is currently a no-args message handler - it would probably still get the arguments to be honest, but at that point `update.getText()` has the entire text in it. Needs to be something like `getKeywords(update.getText, "listitems")`
