### ISSUE TITLE
Bugs on attack-all items

### ISSUE THREAD

**Issue by dagwud** [EvanKnowles/SecretFightClub#19]
1. Even if damage is negative (is a global heal item) it still inflicts damage. See “Round of drinks” item

2. ListItems shows two squid icons instead of either squid+bomb, squid+radioactive, squid+hospital, squid+pill, etc 
(Squid = item has a spray effect, btw)

**Comment by EvanKnowles** [comment]
Ah - I thought the squids were meant to be on either sad of the damage, to show the splashy-ness.

**Comment by EvanKnowles** [comment]
Not sure about 1., fixed 2. by removing the additional squid append.
